# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pds_api_server.models.base_model_ import Model
from pds_api_server.models.capabilities_inner import CapabilitiesInner  # noqa: F401,E501
from pds_api_server import util


class Capabilities(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """Capabilities - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Capabilities':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The capabilities of this Capabilities.  # noqa: E501
        :rtype: Capabilities
        """
        return util.deserialize_model(dikt, cls)
