# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pds_api_server.models.base_model_ import Model
from pds_api_server import util


class ErrorMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: str=None, resource: str=None, query: str=None, message: str=None):  # noqa: E501
        """ErrorMessage - a model defined in Swagger

        :param url: The url of this ErrorMessage.  # noqa: E501
        :type url: str
        :param resource: The resource of this ErrorMessage.  # noqa: E501
        :type resource: str
        :param query: The query of this ErrorMessage.  # noqa: E501
        :type query: str
        :param message: The message of this ErrorMessage.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'url': str,
            'resource': str,
            'query': str,
            'message': str
        }

        self.attribute_map = {
            'url': 'url',
            'resource': 'resource',
            'query': 'query',
            'message': 'message'
        }
        self._url = url
        self._resource = resource
        self._query = query
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The errorMessage of this ErrorMessage.  # noqa: E501
        :rtype: ErrorMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this ErrorMessage.


        :return: The url of this ErrorMessage.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this ErrorMessage.


        :param url: The url of this ErrorMessage.
        :type url: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def resource(self) -> str:
        """Gets the resource of this ErrorMessage.


        :return: The resource of this ErrorMessage.
        :rtype: str
        """
        return self._resource

    @resource.setter
    def resource(self, resource: str):
        """Sets the resource of this ErrorMessage.


        :param resource: The resource of this ErrorMessage.
        :type resource: str
        """
        if resource is None:
            raise ValueError("Invalid value for `resource`, must not be `None`")  # noqa: E501

        self._resource = resource

    @property
    def query(self) -> str:
        """Gets the query of this ErrorMessage.


        :return: The query of this ErrorMessage.
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query: str):
        """Sets the query of this ErrorMessage.


        :param query: The query of this ErrorMessage.
        :type query: str
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query

    @property
    def message(self) -> str:
        """Gets the message of this ErrorMessage.


        :return: The message of this ErrorMessage.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ErrorMessage.


        :param message: The message of this ErrorMessage.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
