# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pds_api_server.models.base_model_ import Model
from pds_api_server import util


class PDS4Label(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """PDS4Label - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'PDS4Label':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PDS4Label of this PDS4Label.  # noqa: E501
        :rtype: PDS4Label
        """
        return util.deserialize_model(dikt, cls)
