# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pds_api_server.models.base_model_ import Model
from pds_api_server import util


class Collection(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, title: str=None, description: str=None, instrument: str=None, target: str=None):  # noqa: E501
        """Collection - a model defined in Swagger

        :param id: The id of this Collection.  # noqa: E501
        :type id: str
        :param title: The title of this Collection.  # noqa: E501
        :type title: str
        :param description: The description of this Collection.  # noqa: E501
        :type description: str
        :param instrument: The instrument of this Collection.  # noqa: E501
        :type instrument: str
        :param target: The target of this Collection.  # noqa: E501
        :type target: str
        """
        self.swagger_types = {
            'id': str,
            'title': str,
            'description': str,
            'instrument': str,
            'target': str
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'description': 'description',
            'instrument': 'instrument',
            'target': 'target'
        }
        self._id = id
        self._title = title
        self._description = description
        self._instrument = instrument
        self._target = target

    @classmethod
    def from_dict(cls, dikt) -> 'Collection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The collection of this Collection.  # noqa: E501
        :rtype: Collection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Collection.

        identifier lidvid of the collection  # noqa: E501

        :return: The id of this Collection.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Collection.

        identifier lidvid of the collection  # noqa: E501

        :param id: The id of this Collection.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Collection.


        :return: The title of this Collection.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Collection.


        :param title: The title of this Collection.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this Collection.


        :return: The description of this Collection.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Collection.


        :param description: The description of this Collection.
        :type description: str
        """

        self._description = description

    @property
    def instrument(self) -> str:
        """Gets the instrument of this Collection.

        identifier lidvid of the instrument or procedure generating the data  # noqa: E501

        :return: The instrument of this Collection.
        :rtype: str
        """
        return self._instrument

    @instrument.setter
    def instrument(self, instrument: str):
        """Sets the instrument of this Collection.

        identifier lidvid of the instrument or procedure generating the data  # noqa: E501

        :param instrument: The instrument of this Collection.
        :type instrument: str
        """

        self._instrument = instrument

    @property
    def target(self) -> str:
        """Gets the target of this Collection.

        identifier lidvid of the target of the observation  # noqa: E501

        :return: The target of this Collection.
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target: str):
        """Sets the target of this Collection.

        identifier lidvid of the target of the observation  # noqa: E501

        :param target: The target of this Collection.
        :type target: str
        """

        self._target = target
