# 🏃‍♀️ Imaging
#
# This workflow makes a Docker image for multiple architectures and publishes it to various image
# repositories. Currently, … 🔮
#
# It's typically triggered from an upstream workflow (Roundup) but can be run manually.

---

name: 🌁 Imaging


# Driving Event
# -------------
#
# What event starts this workflow: success from the Roundup.

on:
    repository_dispatch:
        types: [roundup-success]


# What to Do
# ----------
#
# Make and publish Docker images.

jobs:
    imaging:
        name: 🏞 Image Construction & Publication
        runs-on: ubuntu-latest
        steps:
            -
                name: 💳 Docker Hub Identification
                uses: docker/login-action@v1
                with:
                    username: ${{secrets.DOCKERHUB_USERNAME}}
                    password: ${{secrets.DOCKERHUB_TOKEN}}
            -
                name: 💳 Checkout
                uses: actions/checkout@v2
                with:
                    lfs: true
                    fetch-depth: 0
                    token: ${{secrets.ADMIN_GITHUB_TOKEN}}
                    ref: ${{github.event.client_payload.ref}}
            -
                name: 🎰 QEMU Multiple Machine Emulation
                uses: docker/setup-qemu-action@v1
            -
                name: 🚢 Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: 🧱 Image Construction and Publication
                uses: docker/build-push-action@v2
                with:
                    context: ./service/docker
                    file: ./service/docker/Dockerfile
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: ${{secrets.DOCKERHUB_USERNAME}}/registry-api-service:${{github.event.client_payload.image_tag}}

...

# -*- mode: yaml; indent: 4; fill-column: 120; coding: utf-8 -*-
